// build.js — runs during Cloudflare Pages build
// Reads Firebase config from environment variables → writes config.js
// config.js is in .gitignore and never committed to source control

import { writeFileSync } from 'fs';

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'FIREBASE_MEASUREMENT_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
  console.error('Missing environment variables:', missing.join(', '));
  process.exit(1);
}

const config = `// AUTO-GENERATED by build.js — do not edit or commit
export const FIREBASE_CONFIG = {
  apiKey:            '${process.env.FIREBASE_API_KEY}',
  authDomain:        '${process.env.FIREBASE_AUTH_DOMAIN}',
  projectId:         '${process.env.FIREBASE_PROJECT_ID}',
  storageBucket:     '${process.env.FIREBASE_STORAGE_BUCKET}',
  messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
  appId:             '${process.env.FIREBASE_APP_ID}',
  measurementId:     '${process.env.FIREBASE_MEASUREMENT_ID}',
};
`;

writeFileSync('config.js', config);
console.log('config.js generated successfully.');
